### ISSUE TITLE
Card 엔티티의 CostContent 값 변경

### ISSUE THREAD

**Issue by Samsam-lee** [2P3S/2p3s-backend-system#37]
https://github.com/2P3S/2p3s-backend-system/blob/ca44754f4c77ea33efd6d7d7a6cb430958edce29/src/scrum-dice/entities/card.entities.ts#L8-L17

- FIBONACCI_NUMBERS: 0, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
- MODIFIED_FIBONACCI_NUMBERS: 0, 0.5, 1, 2, 3, 5, 8, 13, 20, 40, 100

**CostContent에 이 값들이 모두 필요한게 아닌가 싶습니다!**

**Comment by JeongJaeSoon** [comment]
resolved at https://github.com/2P3S/2p3s-backend-system/commit/61ffcd493ee5ce9470ea1afaf564f3a3301f4eba
