### ISSUE TITLE
[scrum-dice] 한 사람이 여러 번 투표 시에 투표한 카드가 쌓이게 됨

### ISSUE THREAD

**Issue by JeongJaeSoon** [2P3S/2p3s-backend-system#51]
* 카드 정보만 계속 업데이트를 했지만, 원인불상의 이유로 card 는 업데이트 되지만 room 과 vote 의 정보는 업데이트되지 않는 문제가 있다.
* 정답은 cards 의 데이터를 { memberId 를 key : Card 를 value } 로 하도록 하는 것이 좋아보인다

**Comment by JeongJaeSoon** [comment]
첫번째 해결 방법은 좋은 해결방법이 아님
* 사용자에게서 불필요한 카드 제출이 무수히 많이 일어났을 때 순환해야하는 vote 의 cards 배열의  길이가 늘어남
* 한 명이 아닌 여러 명의 사용자가 해당 행위를 할 경우 많은 문제가 발생
* 단순히 특정 사용자가 의미 없는 카드 제출을 많이할 경우를 대비해서, 일정 시간내에 제출 횟수를 제한할 필요도 있긴할듯 - @hyunnnn98 검토

**Comment by JeongJaeSoon** [comment]
vote 에 저장되는 cards 의 데이터를 배열이 아닌 object 형태로 저장하는게 좋은 방법으로 보임 
key 는 memberId, value 는 card data

**Comment by JeongJaeSoon** [comment]
```json
{
    "cards": {
        "member_1": {
            "type": "cost-type",
            "content": 2
        },
       "member_2": {
            "type": "cost-type",
            "content": 3
        },
        "member_3": {
            "type": "no-cost-type",
            "content": "coffee"
        }
    }
}
```

**Comment by hyunnnn98** [comment]
프론트랑 의견조율 완료.
LGTM 👍
