### ISSUE TITLE
[scrum-dice] socket.io system sequence 설계

### ISSUE THREAD

**Issue by Samsam-lee** [2P3S/2p3s-backend-system#7]

**Comment by Samsam-lee** [comment]
[시퀀스 다이어그램 Wiki](https://github.com/2P3S/2p3s-backend-system/wiki/Sequence_Diagram) 에 작성 -ing

**Comment by JeongJaeSoon** [comment]
Miro 로 sequence 초안 작성 후, 중간 리뷰 진행
https://miro.com/app/board/uXjVMSIDdFM=/
